_/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from django.urls import (
    include,
    path,
)

# https://stackoverflow.com/a/21938270/8224218
# redirect /favicon.ico to /static/images/favicon.ico
FaviconView = RedirectView.as_view(url='/static/images/favicon.ico', permanent=True)

urlpatterns = [
    path('favicon.ico', FaviconView),
    path('admin/', include('my_admin.urls')),
    path('api/', include('api.urls')),
    path('account/', include('xtalk_account.urls')),
    path('', include('devicetalk.urls')),
    path('debug/', admin.site.urls)
]

if settings.WEB_SERVER_PREFIX and settings.WEB_SERVER_PREFIX != "/":
    urlpatterns = [url(settings.WEB_SERVER_PREFIX + "/", include(urlpatterns))]

my_admin/urls.py
from django.urls import path

from .views import (
    IndexView,
    BasicFileView,
    LanguageView
)

app_name = 'my_admin'

urlpatterns = [
    path('', IndexView.as_view(), name='index_endpoint'),
    path('file', BasicFileView.as_view(), name='file_endpoint'),
    path('language', LanguageView.as_view(), name='language_endpoint'),
]

xtalk_account/urls.py
from django.urls import path

from .views import (
    AuthCallbackView,
    AuthRedirectionView,
    LogoutView,
)

app_name = 'xtalk_account'

urlpatterns = [
    path('auth', AuthRedirectionView.as_view(), name='auth_redirect_endpoint'),
    path(
        'auth/callback',
        AuthCallbackView.as_view(),
        name='oauth2_redirect_endpoint'
    ),
    path('logout', LogoutView.as_view(), name='logout_endpoint'),
]

my_admin/models.py
# from django.db import models

# Create your models here.

my_admin/views.py
import json

from urllib.parse import parse_qs

from django.contrib.auth import get_user_model
from django.template.response import TemplateResponse
from django.views.generic.base import View

from .utils import (
    remove_file_group,
    update_basicfile
)
from api.models import (
    BasicFile,
    Language
)
from api.utils import (
    DeviceTalkJsonResponse,
    DeviceTalkErrorJsonResponse
)
from xtalk_account.utils import (
    check_login,
    check_is_admin
)


class LanguageView(View):
    http_method_names = [
        'get',
        'put',
        'delete'
    ]

    @check_login
    @check_is_admin
    def get(self, request, *args, **kwargs):
        """ This function return the list of language.
        Query param::
            <None>

        Response format::

            {
                {
                    'state': 'OK',
                    'result': {
                        'languages': [list of language name],
                        'basic_files_map': {
                            language_name: [list of basicfile name],
                        }
                    }
                },
            }
        """
        languages = [
            language.name for language in Language.objects.all()
        ]
        basic_files = {
            language.name: {
                basicfile.id: basicfile.name
                for basicfile in language.basicfile_set.all()
            }
            for language in Language.objects.all()
        }
        return DeviceTalkJsonResponse({
            'languages': languages,
            'basic_files_map': basic_files
        })

    @check_login
    @check_is_admin
    def put(self, request, *args, **kwargs):
        """ This function create new language
        Request format::
            {
                'language': language name
            }

        Sucess Response format::
            {
                {
                    'state': 'OK',
                    'result': {}
                },
            }

        Error Response format::
            {
                {
                    'state': 'error',
                    'reason': '...'
                },
            }
        """
        body = json.loads(request.body)
        language = body.get('data', {}).get('language')
        try:
            Language.objects.create(name=language)
        except:
            return DeviceTalkErrorJsonResponse(
                f'Language "{language}" already exist or other error.',
                400
            )
        return DeviceTalkJsonResponse()

    @check_login
    @check_is_admin
    def delete(self, request, *args, **kwargs):
        """ This function delete a language
        Request format::
            {
                'language': language name
            }

        Sucess Response format::
            {
                {
                    'state': 'OK',
                    'result': {}
                },
            }

        Error Response format::
            {
                {
                    'state': 'error',
                    'reason': '...'
                },
            }
        """
        body = json.loads(request.body)
        language = body.get('data', {}).get('language')
        try:
            language_object = Language.objects.get(name=language)
        except:
            return DeviceTalkErrorJsonResponse(f'Language "{language}" not found.')
        basicfile_list = [b for b in language_object.basicfile_set.all()]
        for basicfile_object in basicfile_list:
            file_objects = [f for f in basicfile_object.file_set.all()]
            for file in file_objects:
                file.delete()
            basicfile_object.delete()
        language_object.delete()
        return DeviceTalkJsonResponse()


class BasicFileView(View):
    http_method_names = [
        'get',
        'put',
        'post',
        'delete'
    ]

    @check_login
    @check_is_admin
    def get(self, request, *args, **kwargs):
        """ This function return the list of basic files’ information.
        Query param::
            language: language's name
            basicfile: basicfile's id

        Response format::

            {
                {
                    'state': 'OK',
                    'result': {
                        'files': [
                            {
                                'uuid': 'abc123...',
                                'file_path': '/example/foo.py'
                            }, ...
                        ]
                    }
                },
            }
        """
        qs_body = parse_qs(request.GET.urlencode())
        language = qs_body.get('language', [None])[0]
        basicfile = qs_body.get('basicfile', [None])[0]

        try:
            basic_file_object = BasicFile.objects.get(
                id=basicfile
            )
        except:
            return DeviceTalkJsonResponse({'files': []})
        if basic_file_object.language.name != language:
            return DeviceTalkErrorJsonResponse(
                'Language name and Basicfile ID not match', 400)

        files_list = [
            {
                'uuid': file.uuid,
                'file_path': file.file_path
            }
            for file in basic_file_object.file_set.all()
        ]
        return DeviceTalkJsonResponse({
            'files': files_list
        })

    @check_login
    @check_is_admin
    def put(self, request, *args, **kwargs):
        """ Create new Basic File.
        Request format::
            {
                'state': "completed" | "failed",
                'file_upload_id': 10,
                'basicfile_name': 'Default',  # name of basicfile
                'language': 'Python'  # the language this basicfile belong to
            }

        Sucess Response format::
            {
                {
                    'state': 'OK',
                    'result': {}
                },
            }

        Error Response format::
            {
                {
                    'state': 'error',
                    'reason': '...'
                },
            }
        """
        body = json.loads(request.body)
        err_msg, code = update_basicfile(
            body.get('data', {}).get('file_upload_id'),
            body.get('data', {}).get('state'),
            body.get('data', {}).get('language'),
            body.get('data', {}).get('basicfile_name'),
            is_create=True,
        )

        if err_msg:
            return DeviceTalkErrorJsonResponse(err_msg, code)
        else:
            return DeviceTalkJsonResponse()

    @check_login
    @check_is_admin
    def post(self, request, *args, **kwargs):
        """ Update exist Basic File.
        Request format::
            {
                'state': "completed" | "failed",
                'file_upload_id': 10,
                'basicfile_name': 'Default',  # name of basicfile
                'language': 'Python'  # the language this basicfile belong to
            }

        Sucess Response format::
            {
                {
                    'state': 'OK',
                    'result': {}
                },
            }

        Error Response format::
            {
                {
                    'state': 'error',
                    'reason': '...'
                },
            }
        """
        body = json.loads(request.body)
        err_msg, code = update_basicfile(
            body.get('data', {}).get('file_upload_id'),
            body.get('data', {}).get('state'),
            body.get('data', {}).get('language'),
            body.get('data', {}).get('basicfile_name'),
            is_create=False,
        )

        if err_msg:
            return DeviceTalkErrorJsonResponse(err_msg, code)
        else:
            return DeviceTalkJsonResponse()

    @check_login
    @check_is_admin
    def delete(self, request, *args, **kwargs):
        """ This function check the uploaded file's format.
        Request format::
            {
                'basicfile': 10,  # id of basicfile
                'language': 'Python'  # the language this basicfile belong to
            }

        Sucess Response format::
            {
                {
                    'state': 'OK',
                    'result': {}
                },
            }

        Error Response format::
            {
                {
                    'state': 'error',
                    'reason': '...'
                },
            }
        """
        body = json.loads(request.body)
        language = body.get('data', {}).get('language')
        basicfile = body.get('data', {}).get('basicfile')
        try:
            basicfile_object = BasicFile.objects.get(
                id=basicfile,
                language__name=language
            )
        except:
            return DeviceTalkErrorJsonResponse('Basicfile not found.', 400)
        remove_file_group(basicfile_object)
        return DeviceTalkJsonResponse()


class IndexView(View):
    """
    This View return the my_admin's index page.
    """
    http_method_names = [
        'get',
    ]

    def get(self, request, *args, **kwargs):
        if 0: #not request.user.is_authenticated:
            context = {
                'language': '',
                'languages': [],
                'username': '',
                'is_admin': False
            }
            return TemplateResponse(request, 'my_admin.html', context)

        # Get all language name
        languages = [
            item.name for item in Language.objects.all()
        ]

        
        
#        user_object = get_user_model().objects.get(
#            username=request.user.username
#        )
        


        context = {
            'language': languages[0],
            'languages': languages,
            'username':  'ADMIN',#user_object.username,
            'is_admin': 1, #user_object.is_admin
        }

my_admin/templates/my_admin.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>DeviceTalk Admin</title>
    <link href="{% static 'css/device-talk.css' %}" rel="stylesheet" />
  </head>

  <body onload="init()">
    {% csrf_token %}
    <nav id="nav-ctx">
      <div class="nav-container">
        <div class="nav-inner">
          <div><h1>Admin</h1></div>
          <div>
            {% if request.user.is_authenticated %}
            Login as : {{ username }}
            <span>
              <a href="{% url "xtalk_account:logout_endpoint" %}"> Logout</a>
            </span>
            {% else %}
            <span>
              <a href="{% url "xtalk_account:auth_redirect_endpoint" %}"> Login</a>
            </span>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>

    {% if is_admin %}
    {% verbatim %}
    <div class="main-container" id="app">
      <!-- modal -->
      <div class="modal-container" v-show="file_upload_state.show">
        <div class="modal-inner">
          <h3>Files Upload</h3>
          <table>
            <tr v-for="(value, relativ_path) in file_upload_state.files">
                <td>{{ relativ_path }}</td>
                <td><progress-bar
                      endpoint_prefix="../api/file/"
                      :ref="'file-'+value.index"
                      :file="value.file"
                      :index="value.index"
                      :uuid="value.uuid"
                      @upload_completed="upload_next"
                      @upload_fail="upload_fail">
                    </progress-bar>
                </td>
            </tr>
          </table>
        </div>
      </div> <!-- modal end-->
      <div class="main-inner">
        <div class="tab-ctx">
          <div class="table-wrapper">
            <table>
              <tr>
                <td>Language</td>
                <td>
                  <select v-model="language" v-on:change="language_change()">
                    <option v-for="(language) in languages" :value='language'>{{ language }}</option>
                  </select>
                </td>
                <td>
                  <a class="text-button" @click="language_add()">Add</a>
                </td>
                <td>
                  <a class="text-button" @click="language_delete()">Delete</a>
                </td>
              </tr>
              <tr>
                <td>Basic File</td>
                <td>
                  <select v-model="basicfile" v-on:change="basicfile_change()">
                    <option value="-1" style="display:none;">(Please add new basic file)</option>
                    <option v-for="(name, id) in basicfiles" :value='id'>{{ name }}</option>
                  </select>
                </td>
                <td><a class="text-button" @click="add_basicfile()">Add</a>
                    <input id="add-file" type="file" v-on:change="handleFiles($event, 'PUT')" webkitdirectory directory multiple style="display:none; visibility:hidden;" />
                </td>
                <td><a class="text-button" @click="delete_basicfile()">Delete</a></td>
              </tr>
              <tr>
                <td>
                    <button v-on:click="update_basicfile()" v-show="basicfile !== -1">Update Basic File</button>
                    <input id="update-file" type="file" v-on:change="handleFiles($event, 'POST')" webkitdirectory directory multiple style="display:none; visibility:hidden;" />
                </td>
                <td colspan="3">
                    <p v-for="file in files" v-on:dblclick="fileDbClick(file.uuid)">{{ file.file_path }}</p>
                </td>
              </tr>
            </table>
          </div>
        </div>
        <a href="../debug/">Django admin</a>
      </div>
    </div>
    {% endverbatim %}
    {% else %}
    <div class="main-container" id="app">
      <div class="main-inner">
        <div>(Please login as admin)</div>
      </div>
    </div>
    {% endif %}
  </body>

  {% if is_admin %}
  <script src="https://cdn.jsdelivr.net/npm/vue@2.5.17/dist/vue.js"></script>
  <script src="{% static 'js/progress_bar.js' %}"></script>
  <script src="{% static 'js/utils.js' %}"></script>
  <script src="{% static 'js/my_admin.js' %}"></script>
  {% endif %}

  <script>
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
    const _language = '{{ language|safe }}';
    const _languages = {{ languages|safe }};
  </script>
</html>